# Generated by Django 4.1.6 on 2023-02-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_comment_table_alter_likes_table'),
    ]

    operations = [
    ]
