# Generated by Django 4.1.6 on 2023-02-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channeldata_table'),
    ]

    operations = [
    ]
