# Generated by Django 4.1.6 on 2023-02-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_categories_table_alter_playlists_table_and_more'),
    ]

    operations = [
    ]
